### ISSUE TITLE
source code block too long

### ISSUE THREAD

**Issue by ZhangYet** [vincentdoerig/latex-css#26]
When using latex.css to generate html from my org-mode note, the source code sometimes will be too long and out of <pre> area as below:
![example](https://user-images.githubusercontent.com/5897454/85226342-9ffbb500-b409-11ea-9709-9449032085f7.png)

**Comment by ZhangYet** [comment]
I tried to solved this problem in this way: https://github.com/vincentdoerig/latex-css/pull/27

I wonder if you had a better way.

**Comment by vincentdoerig** [comment]
This should not be happening I think, because the `<pre>` element is set to overflow when the content is too big. This means that the element should be scrollable when the content exceeds its width. Could you maybe provide the code that caused the issue as well as your browser/OS? Cheers!

**Comment by ZhangYet** [comment]
Here is the html source code: https://gist.github.com/ZhangYet/13da5cd6041108cb2a95c04c5e680548

I tried it in Google Chrome 81.0.4044.129 and Safari 13.1.1 (14609.2.9.1.3).

My OS is Mac OS 10.14.6. 

Thx.

**Comment by vincentdoerig** [comment]
I found the issue. org (probably) is adding this snippet `pre.src {
position: relative;
overflow: visible;
padding-top: 1.2em;
}` [here](https://gist.github.com/ZhangYet/13da5cd6041108cb2a95c04c5e680548#file-grpc_note-html-L43) to `<pre>` which disables the x-overflow. You can fix it by overwriting latex.css using `pre { overflow: auto !important; }`.

**Comment by ZhangYet** [comment]
It works! thx!
