### ISSUE TITLE
mathjax cdn broken

### ISSUE THREAD

**Issue by jonathanronen** [vincentdoerig/latex-css#29]
Hi there! I love this template.

The mathjax cdn appears to be broken:

`Loading failed for the <script> with source “https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js”. latex.now.sh:377:1`

**Comment by vincentdoerig** [comment]
Hi! The link seems to work on my end. Maybe something is blocking the script from loading on your device?

**Comment by jonathanronen** [comment]
You're right! Thanks :)
