### ISSUE TITLE
Turkish Language

### ISSUE THREAD

**Issue by acarzfr** [vincentdoerig/latex-css#31]
Can you add the tr.css file for the LaTeX.css file? I tried it myself and could not get authorization. It should be:

`:lang(tr) .theorem::before { content: 'Teorem ' counter(theorem) '. ' !important; }
:lang(tr) .lemma::before { content: 'Lemma ' counter(theorem) '. ' !important; }
:lang(tr) .proof::before { content: 'Kanıt. ' attr(title) !important; }
:lang(tr) .definition::before { content: 'Tanım ' counter(definition) '. ' !important; }`

**Comment by acarzfr** [comment]
I think I made a suggestion :)

**Comment by vincentdoerig** [comment]
Thanks, I opened PR #32 with your code. Please double-check and I will then be able to merge.

**Comment by acarzfr** [comment]
I checked. The responses I suggest are correct. Thank you.

Vincent Dörig <notifications@github.com>, 27 Ağu 2020 Per, 19:33 tarihinde
şunu yazdı:

**Comment by vincentdoerig** [comment]
Cheers!

**Comment by acarzfr** [comment]
Cheers!

Vincent Dörig <notifications@github.com>, 27 Ağu 2020 Per, 22:09
tarihinde şunu yazdı:
