### ISSUE TITLE
Add support of Russian

### ISSUE THREAD

**Issue by cheremovsky** [vincentdoerig/latex-css#38]
Hi there.
Awesome project, thanks!
Would it be difficult to add support of Russian language?
The fonts are not quite right in Russian for now.

**Comment by cheremovsky** [comment]
Ah, I see, Latin Modern does not have Cyrillic support

**Comment by vincentdoerig** [comment]
I think if you use LaTeX.css with the [alternate typeface](https://latex.now.sh/#alternative-typeface) ([libertinus](https://github.com/alerque/libertinus)), it should work since I think it supports cyrillic characters.
