### ISSUE TITLE
How to use latex-css locally?

### ISSUE THREAD

**Issue by Ypot** [vincentdoerig/latex-css#39]
Hi
I am trying to use the style.css locally, but the export results are different. 
I copied the content from https://latex.now.sh/style.css in an plain text file and renamed to latex.css but the appearence is quite worse.

![image](https://user-images.githubusercontent.com/30699014/115142697-69032980-a043-11eb-9d61-d927ee184b45.png)

Left: `<link rel="stylesheet" href="https://latex.now.sh/style.css">`
Right: `<link rel="stylesheet" type="text/css" href="latex.css" />`

**Comment by chuahou** [comment]
style.css contains relative links to font files, e.g.

```
@font-face {
  font-family: 'Latin Modern';
  font-style: normal;
  font-weight: normal;
  font-display: swap;
  src: url('./fonts/LM-regular.woff2') format('woff2'),
    url('./fonts/LM-regular.woff') format('woff'),
    url('./fonts/LM-regular.ttf') format('truetype');
}
```

would need `LM-regular.woff2` etc in the `fonts/` directory. You probably need to replicate this directory structure in your local copy to emulate the same results. As a start, you definitely need [these fonts](https://github.com/vincentdoerig/latex-css/tree/master/fonts).

Personally, I would use a clone of the [repository](https://github.com/vincentdoerig/latex-css) (e.g. as a submodule) to avoid having to replicate relative filepaths manually.

**Comment by Ypot** [comment]
I cloned the repository locally. It works great, thanks!
