### ISSUE TITLE
Wrong code for Danish

### ISSUE THREAD

**Issue by phieri** [vincentdoerig/latex-css#44]
The ISO language code for the Danish language support is wrong. It should be `da` but is `dk`.

Reference: https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

**Comment by vincentdoerig** [comment]
Thanks for this! Fixed in v1.7.0.

**Comment by vincentdoerig** [comment]
Oops, you are totally right. Should be fixed now;)
