### ISSUE TITLE
Consider moving FUNDING.yml to vincentdoerig/.github

### ISSUE THREAD

**Issue by jcbhmr** [vincentdoerig/latex-css#51]
**Disclaimer:** This is a _suggestion_. It's up to you.

If you're looking for more eyes on your funding stuff, you can move the .github/FUNDING.yml file to your special .github repo to apply it automagically to all your repos! [Here's the GitHub page about all the community files that can go in .github repo, .github folder, etc.](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#supported-file-types:~:text=category%20forms.%22-,FUNDING.yml,-A%20FUNDING%20file)

**Comment by vincentdoerig** [comment]
Thanks for the suggestion. I have deleted the FUNDING.yml in this repo and will leave it at that for now, it was of no use anyway.
