### ISSUE TITLE
MathJax doen't work properly

### ISSUE THREAD

**Issue by 0xflotus** [vincentdoerig/latex-css#6]
<img width="685" alt="Bildschirmfoto 2020-05-24 um 14 46 50" src="https://user-images.githubusercontent.com/26602940/82754491-86952800-9dcd-11ea-976e-88fd02a67371.png">

If I look at https://latex.now.sh/, MathJAX is not working for inline TeX

**Comment by benhid** [comment]
Sometimes work, sometimes doesn't. I think this is a problem of _timing_:

To configure MathJax, this library use a global object named `MathJax` inserted between `<script>` and `</script>` tags in the `<body>` section. However, the script that loads MathJax itself is placed in the `<head>` section.

This leads to an undesired behaviour, as MathJax could be loaded first (and it's not trivial to [configure MathJax after it is loaded](https://docs.mathjax.org/en/latest/web/configuration.html#configuring-mathjax-after-it-is-loaded)) in some cases.

I've submitted a PR to place the `MathJax` object just before the main script: https://github.com/vincentdoerig/latex-css/pull/15 

Hope it helps!

**Comment by vincentdoerig** [comment]
Should be fixed now (#15). Thank you @benhid.
